// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEOg_Jb6FCHfMAL3w6EFOAgQdPnOp3by0',
    appId: '1:508988353728:android:2f4f789840fcf59ef89125',
    messagingSenderId: '508988353728',
    projectId: 'farm-111',
    databaseURL: 'https://farm-111-default-rtdb.firebaseio.com',
    storageBucket: 'farm-111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4I-_IR_idyXo6EXzoL6x3LeggrGc6t6A',
    appId: '1:508988353728:ios:5539f650a520d634f89125',
    messagingSenderId: '508988353728',
    projectId: 'farm-111',
    databaseURL: 'https://farm-111-default-rtdb.firebaseio.com',
    storageBucket: 'farm-111.appspot.com',
    androidClientId: '508988353728-1ivhaqg5j7qef2m3sdq67n2cdunee62n.apps.googleusercontent.com',
    iosClientId: '508988353728-dhg0kh98tvvubae0gcdcbdcjt9hg15ae.apps.googleusercontent.com',
    iosBundleId: 'com.example.mlscHackathon',
  );
}
