// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFhpY-cR9Ug1-7lpZ9OP2f9HkeOW_JaLI',
    appId: '1:420268722966:web:76f4809ec6aa3afaa91e37',
    messagingSenderId: '420268722966',
    projectId: 'hackathon-111',
    authDomain: 'hackathon-111.firebaseapp.com',
    databaseURL: 'https://hackathon-111-default-rtdb.firebaseio.com',
    storageBucket: 'hackathon-111.appspot.com',
    measurementId: 'G-L6LEJRYBNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCaes0UZsQhe7m5Pkud1xpUhelvAmByRQ',
    appId: '1:420268722966:android:5df494bfd08bfebda91e37',
    messagingSenderId: '420268722966',
    projectId: 'hackathon-111',
    databaseURL: 'https://hackathon-111-default-rtdb.firebaseio.com',
    storageBucket: 'hackathon-111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgT0fo3Z3u3UJ_nhspu_4yaQPds1YEZEM',
    appId: '1:420268722966:ios:82a4b628deb3b73ca91e37',
    messagingSenderId: '420268722966',
    projectId: 'hackathon-111',
    databaseURL: 'https://hackathon-111-default-rtdb.firebaseio.com',
    storageBucket: 'hackathon-111.appspot.com',
    iosClientId: '420268722966-22p0oom4sdrnlkk70lcuulatt2u83sfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgT0fo3Z3u3UJ_nhspu_4yaQPds1YEZEM',
    appId: '1:420268722966:ios:82a4b628deb3b73ca91e37',
    messagingSenderId: '420268722966',
    projectId: 'hackathon-111',
    databaseURL: 'https://hackathon-111-default-rtdb.firebaseio.com',
    storageBucket: 'hackathon-111.appspot.com',
    iosClientId: '420268722966-22p0oom4sdrnlkk70lcuulatt2u83sfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon',
  );
}
